/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ChatRole = IDL.Variant({
  'user' : IDL.Null,
  'assistant' : IDL.Null,
});
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'role' : ChatRole,
});
export const ChatRequest = IDL.Record({ 'messages' : IDL.Vec(ChatMessage) });
export const Timestamp = IDL.Int;
export const ChatResponse = IDL.Record({
  'timestamp' : Timestamp,
  'reply' : IDL.Text,
});
export const ModuleId = IDL.Nat;
export const LearningModule = IDL.Record({
  'id' : ModuleId,
  'title' : IDL.Text,
  'icon' : IDL.Text,
  'tips' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'article' : IDL.Text,
  'category' : IDL.Text,
});
export const ResourceId = IDL.Nat;
export const ResourceCategory = IDL.Variant({
  'expertGuidance' : IDL.Null,
  'wellnessArticles' : IDL.Null,
  'emergencySupport' : IDL.Null,
  'parentingTips' : IDL.Null,
});
export const Resource = IDL.Record({
  'id' : ResourceId,
  'title' : IDL.Text,
  'link' : IDL.Text,
  'description' : IDL.Text,
  'category' : ResourceCategory,
});
export const UserId = IDL.Principal;
export const UserProfile = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'joinedAt' : Timestamp,
  'childrenAges' : IDL.Vec(IDL.Nat),
});
export const ProgressStatus = IDL.Variant({
  'notStarted' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const ModuleProgress = IDL.Record({
  'moduleId' : ModuleId,
  'status' : ProgressStatus,
  'bookmarked' : IDL.Bool,
});
export const WorkshopId = IDL.Nat;
export const Workshop = IDL.Record({
  'id' : WorkshopId,
  'title' : IDL.Text,
  'registeredCount' : IDL.Nat,
  'maxCapacity' : IDL.Nat,
  'description' : IDL.Text,
  'facilitator' : IDL.Text,
  'dateTime' : Timestamp,
});
export const FeedbackId = IDL.Nat;
export const Feedback = IDL.Record({
  'id' : FeedbackId,
  'submittedAt' : Timestamp,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'rating' : IDL.Nat,
  'parentName' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'id' : FeedbackId,
  'content' : IDL.Text,
  'submittedAt' : Timestamp,
  'parentName' : IDL.Text,
});

export const idlService = IDL.Service({
  'chat' : IDL.Func([ChatRequest], [ChatResponse], []),
  'getDailyTip' : IDL.Func([], [IDL.Text], ['query']),
  'getModule' : IDL.Func([ModuleId], [IDL.Opt(LearningModule)], ['query']),
  'getMyBookmarks' : IDL.Func([], [IDL.Vec(Resource)], []),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
  'getMyProgress' : IDL.Func([], [IDL.Vec(ModuleProgress)], []),
  'getMyWorkshops' : IDL.Func([], [IDL.Vec(Workshop)], []),
  'getWorkshop' : IDL.Func([WorkshopId], [IDL.Opt(Workshop)], ['query']),
  'isRegisteredForWorkshop' : IDL.Func([WorkshopId], [IDL.Bool], []),
  'listFeedbacks' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
  'listModules' : IDL.Func([], [IDL.Vec(LearningModule)], ['query']),
  'listResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
  'listResourcesByCategory' : IDL.Func(
      [ResourceCategory],
      [IDL.Vec(Resource)],
      ['query'],
    ),
  'listTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'listWorkshops' : IDL.Func([], [IDL.Vec(Workshop)], ['query']),
  'registerForWorkshop' : IDL.Func([WorkshopId], [IDL.Bool], []),
  'removeBookmark' : IDL.Func([ResourceId], [], []),
  'saveBookmark' : IDL.Func([ResourceId], [], []),
  'submitFeedback' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [Feedback],
      [],
    ),
  'submitTestimonial' : IDL.Func([IDL.Text, IDL.Text], [Testimonial], []),
  'updateProgress' : IDL.Func([ModuleId, ProgressStatus, IDL.Bool], [], []),
  'upsertMyProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat)],
      [UserProfile],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ChatRole = IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null });
  const ChatMessage = IDL.Record({ 'content' : IDL.Text, 'role' : ChatRole });
  const ChatRequest = IDL.Record({ 'messages' : IDL.Vec(ChatMessage) });
  const Timestamp = IDL.Int;
  const ChatResponse = IDL.Record({
    'timestamp' : Timestamp,
    'reply' : IDL.Text,
  });
  const ModuleId = IDL.Nat;
  const LearningModule = IDL.Record({
    'id' : ModuleId,
    'title' : IDL.Text,
    'icon' : IDL.Text,
    'tips' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'article' : IDL.Text,
    'category' : IDL.Text,
  });
  const ResourceId = IDL.Nat;
  const ResourceCategory = IDL.Variant({
    'expertGuidance' : IDL.Null,
    'wellnessArticles' : IDL.Null,
    'emergencySupport' : IDL.Null,
    'parentingTips' : IDL.Null,
  });
  const Resource = IDL.Record({
    'id' : ResourceId,
    'title' : IDL.Text,
    'link' : IDL.Text,
    'description' : IDL.Text,
    'category' : ResourceCategory,
  });
  const UserId = IDL.Principal;
  const UserProfile = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'joinedAt' : Timestamp,
    'childrenAges' : IDL.Vec(IDL.Nat),
  });
  const ProgressStatus = IDL.Variant({
    'notStarted' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const ModuleProgress = IDL.Record({
    'moduleId' : ModuleId,
    'status' : ProgressStatus,
    'bookmarked' : IDL.Bool,
  });
  const WorkshopId = IDL.Nat;
  const Workshop = IDL.Record({
    'id' : WorkshopId,
    'title' : IDL.Text,
    'registeredCount' : IDL.Nat,
    'maxCapacity' : IDL.Nat,
    'description' : IDL.Text,
    'facilitator' : IDL.Text,
    'dateTime' : Timestamp,
  });
  const FeedbackId = IDL.Nat;
  const Feedback = IDL.Record({
    'id' : FeedbackId,
    'submittedAt' : Timestamp,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'rating' : IDL.Nat,
    'parentName' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'id' : FeedbackId,
    'content' : IDL.Text,
    'submittedAt' : Timestamp,
    'parentName' : IDL.Text,
  });
  
  return IDL.Service({
    'chat' : IDL.Func([ChatRequest], [ChatResponse], []),
    'getDailyTip' : IDL.Func([], [IDL.Text], ['query']),
    'getModule' : IDL.Func([ModuleId], [IDL.Opt(LearningModule)], ['query']),
    'getMyBookmarks' : IDL.Func([], [IDL.Vec(Resource)], []),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
    'getMyProgress' : IDL.Func([], [IDL.Vec(ModuleProgress)], []),
    'getMyWorkshops' : IDL.Func([], [IDL.Vec(Workshop)], []),
    'getWorkshop' : IDL.Func([WorkshopId], [IDL.Opt(Workshop)], ['query']),
    'isRegisteredForWorkshop' : IDL.Func([WorkshopId], [IDL.Bool], []),
    'listFeedbacks' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
    'listModules' : IDL.Func([], [IDL.Vec(LearningModule)], ['query']),
    'listResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
    'listResourcesByCategory' : IDL.Func(
        [ResourceCategory],
        [IDL.Vec(Resource)],
        ['query'],
      ),
    'listTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'listWorkshops' : IDL.Func([], [IDL.Vec(Workshop)], ['query']),
    'registerForWorkshop' : IDL.Func([WorkshopId], [IDL.Bool], []),
    'removeBookmark' : IDL.Func([ResourceId], [], []),
    'saveBookmark' : IDL.Func([ResourceId], [], []),
    'submitFeedback' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [Feedback],
        [],
      ),
    'submitTestimonial' : IDL.Func([IDL.Text, IDL.Text], [Testimonial], []),
    'updateProgress' : IDL.Func([ModuleId, ProgressStatus, IDL.Bool], [], []),
    'upsertMyProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat)],
        [UserProfile],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };