/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage { 'content' : string, 'role' : ChatRole }
export interface ChatRequest { 'messages' : Array<ChatMessage> }
export interface ChatResponse { 'timestamp' : Timestamp, 'reply' : string }
export type ChatRole = { 'user' : null } |
  { 'assistant' : null };
export interface Feedback {
  'id' : FeedbackId,
  'submittedAt' : Timestamp,
  'email' : string,
  'message' : string,
  'rating' : bigint,
  'parentName' : string,
}
export type FeedbackId = bigint;
export interface LearningModule {
  'id' : ModuleId,
  'title' : string,
  'icon' : string,
  'tips' : Array<string>,
  'description' : string,
  'article' : string,
  'category' : string,
}
export type ModuleId = bigint;
export interface ModuleProgress {
  'moduleId' : ModuleId,
  'status' : ProgressStatus,
  'bookmarked' : boolean,
}
export type ProgressStatus = { 'notStarted' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface Resource {
  'id' : ResourceId,
  'title' : string,
  'link' : string,
  'description' : string,
  'category' : ResourceCategory,
}
export type ResourceCategory = { 'expertGuidance' : null } |
  { 'wellnessArticles' : null } |
  { 'emergencySupport' : null } |
  { 'parentingTips' : null };
export type ResourceId = bigint;
export interface Testimonial {
  'id' : FeedbackId,
  'content' : string,
  'submittedAt' : Timestamp,
  'parentName' : string,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'bio' : string,
  'name' : string,
  'joinedAt' : Timestamp,
  'childrenAges' : Array<bigint>,
}
export interface Workshop {
  'id' : WorkshopId,
  'title' : string,
  'registeredCount' : bigint,
  'maxCapacity' : bigint,
  'description' : string,
  'facilitator' : string,
  'dateTime' : Timestamp,
}
export type WorkshopId = bigint;
export interface _SERVICE {
  'chat' : ActorMethod<[ChatRequest], ChatResponse>,
  'getDailyTip' : ActorMethod<[], string>,
  'getModule' : ActorMethod<[ModuleId], [] | [LearningModule]>,
  'getMyBookmarks' : ActorMethod<[], Array<Resource>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getMyProgress' : ActorMethod<[], Array<ModuleProgress>>,
  'getMyWorkshops' : ActorMethod<[], Array<Workshop>>,
  'getWorkshop' : ActorMethod<[WorkshopId], [] | [Workshop]>,
  'isRegisteredForWorkshop' : ActorMethod<[WorkshopId], boolean>,
  'listFeedbacks' : ActorMethod<[], Array<Feedback>>,
  'listModules' : ActorMethod<[], Array<LearningModule>>,
  'listResources' : ActorMethod<[], Array<Resource>>,
  'listResourcesByCategory' : ActorMethod<[ResourceCategory], Array<Resource>>,
  'listTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'listWorkshops' : ActorMethod<[], Array<Workshop>>,
  'registerForWorkshop' : ActorMethod<[WorkshopId], boolean>,
  'removeBookmark' : ActorMethod<[ResourceId], undefined>,
  'saveBookmark' : ActorMethod<[ResourceId], undefined>,
  'submitFeedback' : ActorMethod<[string, string, bigint, string], Feedback>,
  'submitTestimonial' : ActorMethod<[string, string], Testimonial>,
  'updateProgress' : ActorMethod<
    [ModuleId, ProgressStatus, boolean],
    undefined
  >,
  'upsertMyProfile' : ActorMethod<[string, string, Array<bigint>], UserProfile>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];