/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Workshop {
    id: WorkshopId;
    title: string;
    registeredCount: bigint;
    maxCapacity: bigint;
    description: string;
    facilitator: string;
    dateTime: Timestamp;
}
export type ModuleId = bigint;
export type Timestamp = bigint;
export interface Testimonial {
    id: FeedbackId;
    content: string;
    submittedAt: Timestamp;
    parentName: string;
}
export interface Feedback {
    id: FeedbackId;
    submittedAt: Timestamp;
    email: string;
    message: string;
    rating: bigint;
    parentName: string;
}
export type UserId = Principal;
export interface ChatResponse {
    timestamp: Timestamp;
    reply: string;
}
export interface ChatRequest {
    messages: Array<ChatMessage>;
}
export type WorkshopId = bigint;
export interface Resource {
    id: ResourceId;
    title: string;
    link: string;
    description: string;
    category: ResourceCategory;
}
export interface ChatMessage {
    content: string;
    role: ChatRole;
}
export interface LearningModule {
    id: ModuleId;
    title: string;
    icon: string;
    tips: Array<string>;
    description: string;
    article: string;
    category: string;
}
export type FeedbackId = bigint;
export type ResourceId = bigint;
export interface ModuleProgress {
    moduleId: ModuleId;
    status: ProgressStatus;
    bookmarked: boolean;
}
export interface UserProfile {
    id: UserId;
    bio: string;
    name: string;
    joinedAt: Timestamp;
    childrenAges: Array<bigint>;
}
export enum ChatRole {
    user = "user",
    assistant = "assistant"
}
export enum ProgressStatus {
    notStarted = "notStarted",
    completed = "completed",
    inProgress = "inProgress"
}
export enum ResourceCategory {
    expertGuidance = "expertGuidance",
    wellnessArticles = "wellnessArticles",
    emergencySupport = "emergencySupport",
    parentingTips = "parentingTips"
}
export interface backendInterface {
    chat(request: ChatRequest): Promise<ChatResponse>;
    getDailyTip(): Promise<string>;
    getModule(id: ModuleId): Promise<LearningModule | null>;
    getMyBookmarks(): Promise<Array<Resource>>;
    getMyProfile(): Promise<UserProfile | null>;
    getMyProgress(): Promise<Array<ModuleProgress>>;
    getMyWorkshops(): Promise<Array<Workshop>>;
    getWorkshop(id: WorkshopId): Promise<Workshop | null>;
    isRegisteredForWorkshop(workshopId: WorkshopId): Promise<boolean>;
    listFeedbacks(): Promise<Array<Feedback>>;
    listModules(): Promise<Array<LearningModule>>;
    listResources(): Promise<Array<Resource>>;
    listResourcesByCategory(category: ResourceCategory): Promise<Array<Resource>>;
    listTestimonials(): Promise<Array<Testimonial>>;
    listWorkshops(): Promise<Array<Workshop>>;
    registerForWorkshop(workshopId: WorkshopId): Promise<boolean>;
    removeBookmark(resourceId: ResourceId): Promise<void>;
    saveBookmark(resourceId: ResourceId): Promise<void>;
    submitFeedback(parentName: string, email: string, rating: bigint, message: string): Promise<Feedback>;
    submitTestimonial(parentName: string, content: string): Promise<Testimonial>;
    updateProgress(moduleId: ModuleId, status: ProgressStatus, bookmark: boolean): Promise<void>;
    upsertMyProfile(name: string, bio: string, childrenAges: Array<bigint>): Promise<UserProfile>;
}
import type { ChatMessage as _ChatMessage, ChatRequest as _ChatRequest, ChatRole as _ChatRole, LearningModule as _LearningModule, ModuleId as _ModuleId, ModuleProgress as _ModuleProgress, ProgressStatus as _ProgressStatus, Resource as _Resource, ResourceCategory as _ResourceCategory, ResourceId as _ResourceId, UserProfile as _UserProfile, Workshop as _Workshop } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async chat(arg0: ChatRequest): Promise<ChatResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.chat(to_candid_ChatRequest_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.chat(to_candid_ChatRequest_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getDailyTip(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyTip();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyTip();
            return result;
        }
    }
    async getModule(arg0: ModuleId): Promise<LearningModule | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getModule(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getModule(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyBookmarks(): Promise<Array<Resource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBookmarks();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBookmarks();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProgress(): Promise<Array<ModuleProgress>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProgress();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProgress();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyWorkshops(): Promise<Array<Workshop>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyWorkshops();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyWorkshops();
            return result;
        }
    }
    async getWorkshop(arg0: WorkshopId): Promise<Workshop | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkshop(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkshop(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async isRegisteredForWorkshop(arg0: WorkshopId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isRegisteredForWorkshop(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isRegisteredForWorkshop(arg0);
            return result;
        }
    }
    async listFeedbacks(): Promise<Array<Feedback>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFeedbacks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFeedbacks();
            return result;
        }
    }
    async listModules(): Promise<Array<LearningModule>> {
        if (this.processError) {
            try {
                const result = await this.actor.listModules();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listModules();
            return result;
        }
    }
    async listResources(): Promise<Array<Resource>> {
        if (this.processError) {
            try {
                const result = await this.actor.listResources();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listResources();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async listResourcesByCategory(arg0: ResourceCategory): Promise<Array<Resource>> {
        if (this.processError) {
            try {
                const result = await this.actor.listResourcesByCategory(to_candid_ResourceCategory_n21(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listResourcesByCategory(to_candid_ResourceCategory_n21(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTestimonials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTestimonials();
            return result;
        }
    }
    async listWorkshops(): Promise<Array<Workshop>> {
        if (this.processError) {
            try {
                const result = await this.actor.listWorkshops();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listWorkshops();
            return result;
        }
    }
    async registerForWorkshop(arg0: WorkshopId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.registerForWorkshop(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerForWorkshop(arg0);
            return result;
        }
    }
    async removeBookmark(arg0: ResourceId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeBookmark(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeBookmark(arg0);
            return result;
        }
    }
    async saveBookmark(arg0: ResourceId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveBookmark(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveBookmark(arg0);
            return result;
        }
    }
    async submitFeedback(arg0: string, arg1: string, arg2: bigint, arg3: string): Promise<Feedback> {
        if (this.processError) {
            try {
                const result = await this.actor.submitFeedback(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitFeedback(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async submitTestimonial(arg0: string, arg1: string): Promise<Testimonial> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTestimonial(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTestimonial(arg0, arg1);
            return result;
        }
    }
    async updateProgress(arg0: ModuleId, arg1: ProgressStatus, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProgress(arg0, to_candid_ProgressStatus_n23(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProgress(arg0, to_candid_ProgressStatus_n23(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async upsertMyProfile(arg0: string, arg1: string, arg2: Array<bigint>): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertMyProfile(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertMyProfile(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_ModuleProgress_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ModuleProgress): ModuleProgress {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_ProgressStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProgressStatus): ProgressStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_ResourceCategory_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResourceCategory): ResourceCategory {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Resource_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Resource): Resource {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Workshop]): Workshop | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LearningModule]): LearningModule | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ResourceId;
    title: string;
    link: string;
    description: string;
    category: _ResourceCategory;
}): {
    id: ResourceId;
    title: string;
    link: string;
    description: string;
    category: ResourceCategory;
} {
    return {
        id: value.id,
        title: value.title,
        link: value.link,
        description: value.description,
        category: from_candid_ResourceCategory_n12(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    moduleId: _ModuleId;
    status: _ProgressStatus;
    bookmarked: boolean;
}): {
    moduleId: ModuleId;
    status: ProgressStatus;
    bookmarked: boolean;
} {
    return {
        moduleId: value.moduleId,
        status: from_candid_ProgressStatus_n18(_uploadFile, _downloadFile, value.status),
        bookmarked: value.bookmarked
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expertGuidance: null;
} | {
    wellnessArticles: null;
} | {
    emergencySupport: null;
} | {
    parentingTips: null;
}): ResourceCategory {
    return "expertGuidance" in value ? ResourceCategory.expertGuidance : "wellnessArticles" in value ? ResourceCategory.wellnessArticles : "emergencySupport" in value ? ResourceCategory.emergencySupport : "parentingTips" in value ? ResourceCategory.parentingTips : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notStarted: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): ProgressStatus {
    return "notStarted" in value ? ProgressStatus.notStarted : "completed" in value ? ProgressStatus.completed : "inProgress" in value ? ProgressStatus.inProgress : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ModuleProgress>): Array<ModuleProgress> {
    return value.map((x)=>from_candid_ModuleProgress_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Resource>): Array<Resource> {
    return value.map((x)=>from_candid_Resource_n10(_uploadFile, _downloadFile, x));
}
function to_candid_ChatMessage_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChatMessage): _ChatMessage {
    return to_candid_record_n5(_uploadFile, _downloadFile, value);
}
function to_candid_ChatRequest_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChatRequest): _ChatRequest {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_ChatRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChatRole): _ChatRole {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_ProgressStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProgressStatus): _ProgressStatus {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_ResourceCategory_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResourceCategory): _ResourceCategory {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    messages: Array<ChatMessage>;
}): {
    messages: Array<_ChatMessage>;
} {
    return {
        messages: to_candid_vec_n3(_uploadFile, _downloadFile, value.messages)
    };
}
function to_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: string;
    role: ChatRole;
}): {
    content: string;
    role: _ChatRole;
} {
    return {
        content: value.content,
        role: to_candid_ChatRole_n6(_uploadFile, _downloadFile, value.role)
    };
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResourceCategory): {
    expertGuidance: null;
} | {
    wellnessArticles: null;
} | {
    emergencySupport: null;
} | {
    parentingTips: null;
} {
    return value == ResourceCategory.expertGuidance ? {
        expertGuidance: null
    } : value == ResourceCategory.wellnessArticles ? {
        wellnessArticles: null
    } : value == ResourceCategory.emergencySupport ? {
        emergencySupport: null
    } : value == ResourceCategory.parentingTips ? {
        parentingTips: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProgressStatus): {
    notStarted: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == ProgressStatus.notStarted ? {
        notStarted: null
    } : value == ProgressStatus.completed ? {
        completed: null
    } : value == ProgressStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChatRole): {
    user: null;
} | {
    assistant: null;
} {
    return value == ChatRole.user ? {
        user: null
    } : value == ChatRole.assistant ? {
        assistant: null
    } : value;
}
function to_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ChatMessage>): Array<_ChatMessage> {
    return value.map((x)=>to_candid_ChatMessage_n4(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
